---
apiVersion: v1
kind: Pod
metadata:
  name: grafana
spec:
  containers:
    - name: grafana
      image: docker.io/grafana/grafana:11.3.0
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
      env:
        - name: GF_SECURITY_ADMIN_USER
          value: admin
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
      volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        - name: grafana-provisioning
          mountPath: /etc/grafana/provisioning/
  volumes:
    - name: grafana-data
      persistentVolumeClaim:
        claimName: grafana-data-pvc
    - name: grafana-provisioning
      hostPath:
        path: ./grafana/provisioning/
  restartPolicy: Always

