---
apiVersion: v1
kind: Pod
metadata:
  name: influxdb
spec:
  containers:
    - name: influxdb
      image: docker.io/influxdb:1.8
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8086
      env:
        - name: INFLUXDB_DB
          value: telegraf
        - name: INFLUXDB_ADMIN_ENABLED
          value: "true"
        - name: INFLUXDB_ADMIN_USER
          value: admin
        - name: INFLUXDB_ADMIN_PASSWORD
          value: admin
        - name: INFLUXDB_USER
          value: telegraf
      volumeMounts:
        - name: influxdb-data
          mountPath: /var/lib/influxdb
  volumes:
    - name: influxdb-data
      persistentVolumeClaim:
        claimName: influxdb-data-pvc
  restartPolicy: Always

