{
 "title": "ISP Watchtower",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "SpeedTest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Download Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "internet_speed",
     "query": "SELECT \"download\" FROM \"internet_speed\"",
     "select": [
      [
       { "params": [ "download" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Servers",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "measurement": "internet_speed",
     "query": "SELECT * FROM \"internet_speed\" ORDER BY \"time\" DESC",
     "select": [
      [
       { "params": [ "jitter" ], "type": "field" }
      ],
      [
       { "params": [ "latency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "internet_speed",
     "query": "SELECT \"upload\" FROM \"internet_speed\"",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Upload/Download ",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "measurement": "internet_speed",
     "query": "SELECT \"download\", \"upload\" FROM \"internet_speed\" ORDER BY time DESC LIMIT 20",
     "select": [
      [
       { "params": [ "download" ], "type": "field" }
      ],
      [
       { "params": [ "upload" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "latency",
     "measurement": "internet_speed",
     "query": "SELECT \"latency\" FROM \"internet_speed\" ORDER BY time DESC LIMIT 20",
     "select": [
      [
       { "params": [ "latency" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Jitter",
     "measurement": "internet_speed",
     "query": "SELECT \"jitter\" FROM \"internet_speed\" ORDER BY time DESC LIMIT 20",
     "select": [
      [
       { "params": [ "jitter" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Time (Primary DNS Servers)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "server" ], "type": "tag" }
       ],
       "measurement": "dns_query",
       "select": [
        [
         { "params": [ "query_time_ms" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "server", "operator": "=", "value": "9.9.9.9" },
        { "condition": "OR", "key": "server", "operator": "=", "value": "1.1.1.1" },
        { "condition": "OR", "key": "server", "operator": "=", "value": "8.8.8.8" }
       ]
      }
     ]
    },
    {
     "title": "Domain Query Time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_domain",
       "groupBy": [
        { "params": [ "domain" ], "type": "tag" }
       ],
       "measurement": "dns_query",
       "select": [
        [
         { "params": [ "query_time_ms" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Query Result Status",
     "type": "state-timeline",
     "description": "Plots result_code (int, success = 0, timeout = 1, error = 2)",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 99 },
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "server::tag" ], "type": "tag" }
       ],
       "measurement": "dns_query",
       "query": "SELECT \"result_code\" FROM \"dns_query\" WHERE $timeFilter GROUP BY \"domain\"",
       "select": [
        [
         { "params": [ "result_code" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Query Time (all)",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "server" ], "type": "tag" }
       ],
       "measurement": "dns_query",
       "select": [
        [
         { "params": [ "query_time_ms" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "ICMP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Response time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_url",
       "groupBy": [
        { "params": [ "url" ], "type": "tag" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "average_response_ms" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Packet Loss",
     "type": "state-timeline",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$tag_url",
       "groupBy": [
        { "params": [ "url" ], "type": "tag" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "percent_packet_loss" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "url", "operator": "!=", "value": "google.com" }
       ]
      }
     ]
    },
    {
     "title": "Standard Deviation",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_url",
       "groupBy": [
        { "params": [ "url" ], "type": "tag" }
       ],
       "measurement": "ping",
       "select": [
        [
         { "params": [ "standard_deviation_ms" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}